### ISSUE TITLE
About duplicate ID

### ISSUE THREAD

**Issue by kamitsu2004** [MizaGBF/Raidfinder#1]
Is it possible for Raidfinder to pass the rescue ID obtained when it is duplicated?
Also, if that feature is not implemented, do you have any plans to implement it in the future?

**Comment by MizaGBF** [comment]
Sorry for the very late reply, I didn't notice the issue.  
I'm not sure what you mean exactly, you can simply uncheck the "Ignore Duplicate Codes" setting if you want dupes to be processed as other codes.

**Comment by kamitsu2004** [comment]
Thank you.
I overlooked that setting.
